### ISSUE TITLE
AF issue still not fixed in the April 14 version

### ISSUE THREAD

**Issue by jiehuang001** [zhanxw/rvtests#17]
Dear Xiaowei:

I just sent an email to your GMAIL. I downloaded your new RVTESTS posted yesterday. For one imputed 5MB chunk, I run RVTESTS using the same command and the same data as before, but I still found negative values in the AF column.  The score test based on the previous version of RVTESTS used 25247 seconds, but the new version took 59095 seconds. The wald test in the new version takes 31316 seconds.

Also,  somehow the new version still shows “version: 20170228”.

So, can you please take a good look, to make sure that the AF issue is indeed resolved? It would be great if you change the version date to the release date so that we are sure that we are using the latest version.

Thank you & best regards,
Jie
![screenshot1](https://cloud.githubusercontent.com/assets/26947455/25067165/0fa5e448-2209-11e7-8e46-3ec2eebca87d.JPG)
![screenshot2](https://cloud.githubusercontent.com/assets/26947455/25067166/13bb57fc-2209-11e7-800c-906251e23488.JPG)

**Comment by zhanxw** [comment]
The version tag indicates that it's not the April 14 version. 
But I will deliver a new version that fixes this issue as well as issue #18

**Comment by jiehuang001** [comment]
It would be really great that you could put a fixed version online today, as soon as possible. I need to run some new analysis and report back to our group tomorrow morning!

best regards,
Jie

**Comment by zhanxw** [comment]
Sorry for the confusion. I was referring to this release: https://github.com/zhanxw/rvtests/releases/tag/v2.0.4

This version should fix this issue. Thanks.
