### ISSUE TITLE
thread count for rvtest

### ISSUE THREAD

**Issue by CanWood** [zhanxw/rvtests#20]
Hi folks,

Although the rvtest binary seems to only use a single core for much of its work, we're seeing thread counts jump to take all available cores on the system.  Is there a way to limit this?  The context is so that we can know what resources to ask for when submitting rvtest jobs to HPC systems where the number of CPUs required must be provided.

Cheers

**Comment by zhanxw** [comment]
RVTESTS uses OpenMP. You can limit number of threads using:
OMP_NUM_THREADS=XX before your rvtests commands.

Which version did you use? This behavior is not what I expected and I would
like fix it.

**Comment by CanWood** [comment]
Thanks for the quick response.  We'll try the OMP_NUM_THREADS=1 and see how we go

Originally we were running rvtests (version: 20160630, git: Unknown) and it was running many cores for quite some time.  We then tested with rvtests (version: 20170228, git: Unknown) and the length of time that it took all of the cores on the box was much decreased. when running the same commands

**Comment by CanWood** [comment]
OMP_NUM_THREADS did the trick.  Now our users can have resource requests that are in line with the tool's use.  Thanks!
