### ISSUE TITLE
no variant name in *.SingleScore.assoc file

### ISSUE THREAD

**Issue by jiehuang001** [zhanxw/rvtests#24]
Dear Xiaowei:

For the *.SingleScore.assoc. file generated by RVTESTS, it contains "CHROM POS REF ALT N_INFORMATIVE" etc.  but, the "ID" field in the VCF is not output. Don't know when you will release a new version, it would be good to display those "ID" field as well. This is the unique identifier for a SNP, right?

Best regards,
jie

**Comment by zhanxw** [comment]
That's related to #14. 
I do have plan to support this feature soon.
Thanks.

**Comment by zhanxw** [comment]
Since 20170613, `--outputID` option is added to address this issue.
