### ISSUE TITLE
VCF Line does not have correct column number and exsiting!

### ISSUE THREAD

**Issue by zishang30** [zhanxw/rvtests#28]
Dear Xiaowei

I have checked single chrosome  vcf.gz file and bgziped chr.all vcf.gz file for generating kinship matrix.
It seems that in chr.all vcf.gz file some VCF line does not have correct column number  as follows:

04-30 14:54 Line [ 8869314 ] does not have correct column number, exiting!
04-30 14:54 Current line has 2251 columns.
05-02 23:51 Line [ 16287134 ] does not have correct column number, exiting!
05-02 23:51 Current line has 861 columns.

Because we already checked single VCF.gz, so this error may be due to the bgzip code for bgziping all chromosome ?

The code for bgzip all chromosome are as follows:
(zcat  chr1_notmonomorph.vcf.gz;
    zgrep -v '^#' chr2_notmonomorph.vcf.gz;
    zgrep -v '^#' chr3_notmonomorph.vcf.gz;
    zgrep -v '^#' chr4_notmonomorph.vcf.gz;
    zgrep -v '^#' chr5_notmonomorph.vcf.gz;
    zgrep -v '^#' chr6_notmonomorph.vcf.gz;
    zgrep -v '^#' chr7_notmonomorph.vcf.gz;
    zgrep -v '^#' chr8_notmonomorph.vcf.gz;
    zgrep -v '^#' chr9_notmonomorph.vcf.gz;
    zgrep -v '^#' chr10_notmonomorph.vcf.gz;
    zgrep -v '^#' chr11_notmonomorph.vcf.gz;
    zgrep -v '^#' chr12_notmonomorph.vcf.gz;
    zgrep -v '^#' chr13_notmonomorph.vcf.gz;
    zgrep -v '^#' chr14_notmonomorph.vcf.gz;
    zgrep -v '^#' chr15_notmonomorph.vcf.gz;
    zgrep -v '^#' chr16_notmonomorph.vcf.gz;
    zgrep -v '^#' chr17_notmonomorph.vcf.gz;
    zgrep -v '^#' chr18_notmonomorph.vcf.gz;
    zgrep -v '^#' chr19_notmonomorph.vcf.gz;
    zgrep -v '^#' chr20_notmonomorph.vcf.gz;
    zgrep -v '^#' chr21_notmonomorph.vcf.gz;
    zgrep -v '^#' chr22_notmonomorph.vcf.gz;
    zgrep -v '^#' chrX_notmonomorph.vcf.gz)| bgzip -c > HRC_chrall.vcf.gz

Is this correct?

In addition, another thing came to my mind:
our statistic plan ask us to use follow command to bgzip and index VCF file:
(grep ^"#" $your_old_vcf; grep -v ^"#" $your_old_vcf | sed 's:^chr::ig' | sort -k1,1n -k2,2n) | bgzip -c > $your_vcf_file 
tabix -f -p vcf $your_vcf_file

this command are used for group-based rare variant tests.

If we don't conduct group-based rare variant tests, should we just use command as follow:
bgzip -c file.vcf > file.vcf.gz
tabix -p vcf file.vcf.gz

Thank you very much!

Best regards

Zishan

**Comment by zhanxw** [comment]
Hi Zishan,

The error message reported line numbers (8869314).
Can you please check line 8869314 and compare that with previous line and the next line? 
I would try to generate a small VCF file with line 8869310  to 8869320, re-run rvtests and see if the problem disappears. If not, the problem is probably the input file. You can attach here, and I will check it.


If you don't perform group-based tests, your command will be fine.

**Comment by zishang30** [comment]
Dear Xiaowei

I re-bgziped all the vcf file and re-check all the vcf.gz use check vcf and it seems this problem maybe resolved. But currently when I use re-bgziped chrall vcf.gz to generate kinship matrix and try to run rvtest, it report as follows:

[ERROR] Cannot find sample [ 890005850 ] from the kinship file!
[ERROR] Failed to load kinship file [ chrall_kinship_matrix.kinship ]

Why this happen....? and how could we check the patient ID between kinshipmatrix and VCF?

Thank you for your reply.

Best regards

Zishan

PS we update the version of rvtest and it seems the newest version could resolve the "segmentation fault".

**Comment by dajiangliu** [comment]
Zhishan:


The ID for the kinship files are in the first two columns. You can compare it with the header of the VCF file.


All the best,
Dajiang
--
Assistant Professor
Dept. of Public Health Sciences
Institute of Personalized Medicine
Penn State College of Medicine, HCAR 2020, Mail Stop R125
Email: dajiang.liu@psu.edu
URL: https://dajiangliu.wordpress.com
Tel: +1-717-531-4178


________________________________
