### ISSUE TITLE
Missing col error in version: 20170228

### ISSUE THREAD

**Issue by SailajaVeda** [zhanxw/rvtests#29]
I am using RVtest Program version: 20170228 and creating a covariance matrix with window size of 500KB, to reduce the size of the matrix. I see the following error in my log files, but the analysis runs to completion.

[ERROR]	Missing 'u1141' column!
[WARN] 	Failed to load spectral decomposition results of the kinship matrix!
[INFO] 	DONE: Spectral decomposition of the kinship matrix succeeded in [ 3.4 ] seconds.

Wondering if anyone else has seen this and if this could be a reason why my Covariance matrices are > 400GB (for  HRC imputed data)  in spite of the requested 500kb window size.
Thanks

**Comment by zhanxw** [comment]
This error happens when the decomposed kinship file does not match the input VCF file.
Did RVTESTS stop after this error popped up?

**Comment by SailajaVeda** [comment]
I am sure that I have used the same vcf file to make the kinship matrix file but using a MAF filter.  Yes the RVTESTS does complete the analysis after the error. The covariance matrix files are really large, ~450GB for HRC imputed data set in 3K samples.

**Comment by dajiangliu** [comment]
the covariance matrix size depends directly on the number of markers in a window. Sample sizes are not directly affecting the size of the cov file. Yet, typically, larger datasets come with larger number of segregating markers. Just FYI.

**Comment by SailajaVeda** [comment]
The study has ~15 m polymorphs. As the analyses are running to completion, is it safe to ignore the error?

**Comment by zhanxw** [comment]
I think it's safe to ignore the error. 
This error happens when the pre-calculated decomposed kinship cannot be used in the analysis. If that happens, RVTESTS just try to decompose the kinship and the computation result should be fine.

**Comment by zhanxw** [comment]
In the new version, I will make this error message more explicit. Thanks.
