### ISSUE TITLE
AF reported as 0 for all variants with FamScore Test

### ISSUE THREAD

**Issue by youngh11** [zhanxw/rvtests#34]
Hello,

My command is as follows:
rvtest --inVcf vcf  --pheno pheno --covar covariate --out out --kinship kinship.output.kinship --dosage DS --single FamScore

The AF column is 0 for all variants. 

If the last flag is changed to --meta score, AF is reported. 
rvtest --inVcf vcf  --pheno pheno --covar covariate --out out --kinship kinship.output.kinship --dosage DS --meta score

AF shows up and all other statistics are the same as with FamScore (_p_-value, ustat, etc).

Thank you!

**Comment by zhanxw** [comment]
I can confirm this problem. I will fix it.

**Comment by zhanxw** [comment]
Is this release fix your issue? https://github.com/zhanxw/rvtests/releases/tag/v2.0.5

**Comment by youngh11** [comment]
That does fix the AF issue, thank you.
