### ISSUE TITLE
Problem using the --meta bolt,boltCov option 

### ISSUE THREAD

**Issue by djthompson1** [zhanxw/rvtests#37]
When I tried to run rvtests using the --meta bolt,boltCov options I get this output:

MetaFamQtlBolt model started Report 'Cannot open binary PLINK file!

Does anyone understand what caused this and how I can avoid it?

Thank you very much!

**Comment by zhanxw** [comment]
You just need to specify a separate binary plink file. e.g.  --boltPlink $binaryPlinkPrefix 
Please read this section of the documentation: https://github.com/zhanxw/rvtests#meta-analysis-tests
