### ISSUE TITLE
What is the file format of gene range file?

### ISSUE THREAD

**Issue by TimingSpace** [zhanxw/rvtests#40]
I use the range file 
FLG NM_002016 chr1 152276780 155000000

But I got the following message:
[INFO]  Loaded [ 2 ] genes.
[INFO]  Impute missing genotype to mean (by default)
[INFO]  Analysis started
[INFO]  Gene FLG has 0 variants, skipping

Is there any mistake in my range file?

Besides, I try to modify vcf2ld_gene.cpp file to print more information, but after compiling, the output doesn't change.

If I want to print out more information, what I should do?

**Comment by zhanxw** [comment]
Please refer to: 
https://github.com/zhanxw/rvtests#specify-groups-eg-burden-unit
