### ISSUE TITLE
"unparsed option" when trying to use *bgen file in version 20171010 

### ISSUE THREAD

**Issue by cerulean10** [zhanxw/rvtests#41]
Hello,

     Based on comments in thread 38,  I am using the 20171010 rvtest version with a viable *bgen file and phenotype file in *ped format (NOT using sample file as was stated these are not supported yet).  

However the program does not seem to recognize the --inBgen flag, please advise. Relevant output is as follows:

Effective Options
    --out test1000_bgen_gp.out
    --covar EA.cov
    --covar-name age,pc1,pc2,pc3
    --sex
    --pheno EA.ped
    --pheno-name EA
    --dosage GP
    --meta score
    --impute drop
    --noweb

Unparsed arguments:  --inBgen testrv1000_GP.bgen

best regards,
Polly

**Comment by zhanxw** [comment]
Please use the latest version. It support the `--inBgen` option. Thanks.
