### ISSUE TITLE
Segmentation fault - burden test skato when run with option --outputRaw 

### ISSUE THREAD

**Issue by manu148** [zhanxw/rvtests#59]
Hi,
I am running skat-o burden test using ucsc refFlat file(b38). The program is crashing with segmentation fault.
For some of the genes/bins the length of fn.c_str() is greater than 255. Since linux has a maximum filename length of 255 characters for most filesystems(including EXT4), the fDump is NULL and segmentation fault occurs in following lines. 
https://github.com/zhanxw/rvtests/blob/a6f79347c6eaf1a8fa7950a42a2be2df32747128/src/Model.h#L5155

Capping the max length 
if (fn.length() > 30) {
        fn = fn.substr(0, 30) + ".data";
}
did solve my problem.

Thanks,
Manu

**Comment by zhanxw** [comment]
Thanks for the tip. I will safe guard the length of file name.

**Comment by bestmichaelbrown** [comment]
Hi, 

I believe I am having this problem too. I am running Burden tests and have no issues when I do not add --outputRaw, but including --outputRaw causes a Segmentation fault. Has this been fixed in version 20190128 (git: 65f00ac2b8a48b52ffae17b2e784dbc39211360d)?

**Comment by zhanxw** [comment]
Yes, the new version is intended to fix that. Can you please try that? Please let me know the result. Thanks.

**Comment by zhanxw** [comment]
Sorry, it is not fixed in 20180128. I will release a new version for that. Sorry for the inconvenience.

**Comment by bestmichaelbrown** [comment]
I tested the latest version and it seems to work just fine now.
Thank you very much, I really appreciate it!
