### ISSUE TITLE
Typo in log file

### ISSUE THREAD

**Issue by zx8754** [zhanxw/rvtests#64]
> [INFO]	Loaded [ X ] sample pheontypes

**pheontypes** should be **phenotypes**

**Comment by zx8754** [comment]
Typos are at:

https://github.com/zhanxw/rvtests/blob/a6f79347c6eaf1a8fa7950a42a2be2df32747128/src/DataLoader.cpp#L102

https://github.com/zhanxw/rvtests/blob/a6f79347c6eaf1a8fa7950a42a2be2df32747128/src/Main.cpp#L601

**Comment by zhanxw** [comment]
Fixed in fdd803534e5deb3f14ff82cdcd5077c36f744737 and dd77055000a0681fb6dea34806ea8a48256a4ee8. 

Thanks.
