### ISSUE TITLE
impute drop cause Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ChinaOK** [zhanxw/rvtests#7]
Hello, 

I try to run rvtests for firth logistic regression. Every time I choose --impute drop, I got the segmentation fault. 

Also I noticed that it seems only the first SNP got p-value calculated.All the rest of SNPs got -nan in the p-value column except the first SNP.

**Comment by zhanxw** [comment]
Bug confirmed. Thanks.

**Comment by zhanxw** [comment]
I think the latest version of rvtests fixed this problem.
Close this issue for now.
