### ISSUE TITLE
MadsonBrowning Pvalue is zero

### ISSUE THREAD

**Issue by zx8754** [zhanxw/rvtests#70]
MadsonBrowning test results have zero values for "PermPvalue", does this mean Pvalue is so small that it is rounded to 0 and we should consider it as "significant", or this Pvalue is supposed to be `NA`?

Here is subset of example output, see gene2:

```
Gene	RANGE	N_INFORMATIVE	NumVar	NumPolyVar	NumPerm	ActualPerm	Stat	NumGreater	NumEqual	PermPvalue
gene1	x	x	3	3	10000	10000	4.79095	672	0	0.0672
gene2	x	x	1	1	10000	10000	1.19513	0	0	0
gene3	x	x	3	3	10000	1000	4.28E-06	1000	0	1

```

**Comment by zx8754** [comment]
Here is a better example, where all tests give "significant" pvalue, while MB is zero:

```
#skatO							
Range	RANGE	N_INFORMATIVE	NumVar	NumPolyVar	Q	rho	Pvalue
geneX	x	x	11	11	58761.7	1	0.000204181

#MadsonBrowning										
Range	RANGE	N_INFORMATIVE	NumVar	NumPolyVar	NumPerm	ActualPerm	Stat	NumGreater	NumEqual	PermPvalue
geneX	x	x	11	11	10000	10000	16.6566	0	0	0

#CMC						
Range	RANGE	N_INFORMATIVE	NumVar	NumPolyVar	NonRefSite	Pvalue
geneX	x	x	11	11	22	0.000121977

#Zeggini					
Range	RANGE	N_INFORMATIVE	NumVar	NumPolyVar	Pvalue
geneX	x	x	11	11	0.000204544
```

**Comment by zhanxw** [comment]
The permutation p-value is exactly zero, and it is calculated based on 10,000 permutations. I think if the number of permutation increases, you will get non-zero p-values for MadsonBrowning test.

**Comment by zx8754** [comment]
I see, this answers my question then, zero means value is very close to zero and is significant. Thank you.
