### ISSUE TITLE
Add phenotype sample filter "--keep"

### ISSUE THREAD

**Issue by zx8754** [zhanxw/rvtests#71]
Similar to plink implement [--keep](https://www.cog-genomics.org/plink/1.9/filter) filter.

> **--keep** accepts a space/tab-delimited text file with family IDs in the first column and within-family IDs in the second column, and removes all unlisted samples from the current analysis. --remove does the same for all listed samples.

**Comment by zhanxw** [comment]
Will the option `--peopleIncludeFile` be helpful?

More on this: 
https://github.com/zhanxw/rvtests#sample-inclusionexclusion
