### ISSUE TITLE
suppy vcf2kinship with known pedigree information (--ped has no effect)

### ISSUE THREAD

**Issue by scogi** [zhanxw/rvtests#79]
Hi!

I just started using rvtests to analyze related samples (families) andn was wondering what the correct way is to supply vcf2kinship with known family structure. The help page tells to use --pedigree to supply vcf2kinship with known pedigree structure (https://github.com/zhanxw/rvtests#related-individual-tests), but this gives the error "unparsed arguments: ---pedigree pedigree.ped. I then tried --ped (info from the help page within the terminal). Vcf2kinship runs trough, but the log file tells "[WARN]  Warning: Specified parameter --ped has no effect." Indeed there is no difference in the generated matrix whether only --bn is used or also --ped is specified. Am I missing something? The ped file is the same holding the phenotype data. Is this an issue? 

Thank you!

best regards
Stefan

**Comment by zhanxw** [comment]
You're right that the ped file was not used. That is the expected behavior, as `--bn` will use the observed genotypes to calculate the kinship. That's the recommended behavior when you have many samples.

**Comment by scogi** [comment]
Thank you. I found my error(s). I had specified --bn, too, although i just wanted to supply a known pedigree file using --ped. Additionally I had additionally specified as second input, additionally to the ped file. 

As a side note: the documentation is ambiguous  about the --ped option. At http://zhanxw.github.io/rvtests/#related-individual-tests and https://genome.sph.umich.edu/wiki/Rvtests#Related_individual_tests the documentation says 

> You can specify --ibs to obtain IBS kinship or use --pedigree input.ped to calculate kinship from known pedigree information.

I  think  it should read as follows, right?

> You can specify --ibs to obtain IBS kinship or use *--ped* input.ped to calculate kinship from known pedigree information.

Using --pedigree gives the error "unparsed argument" to me.

**Comment by cuihaoyue** [comment]
HI, do you use the known pedigree information successfully? I met the same error: [WARN] Warning: Specified parameter --ped has no effect.
And then I rm the --bn, like :
vcf2kinship --inVcf input_5.vcf.gz --ped phenotype.ped --out xxxxx
I got the error:
[INFO]	Empiricial kinship will be calculated.
[WARN]	Warning: Specified parameter --ped has no effect.
[INFO]	Start creating empirical kinship from VCF file.
[INFO]	Using default maximum missing rate = 0.05
[INFO]	Using default minimum MAF = 0.05
[ERROR]	More than one or none of the empirical kinsip calculation methods specified.
