### ISSUE TITLE
output file explanation

### ISSUE THREAD

**Issue by sbaheti** [zhanxw/rvtests#82]
hi 
We ran the single variant analysis on our samples and got the output. Do you know where can i find the explanation of these columns ?
N_INFORMATIVE	N00	N01	N10	N11	 ?

Thanks ! Saurabh

**Comment by zhanxw** [comment]
Sorry for the confusion. 

N_INFORMATIVE: the number of informative samples (e.g., samples with valid genotypes).
N00: the number of reference alleles in the control group
N01: the number of reference alleles in the case group
N10: the number of non-reference alleles in the control group
N11: the number of non-reference alleles in the case group
