### ISSUE TITLE
results for cmcWald

### ISSUE THREAD

**Issue by apampana** [zhanxw/rvtests#85]
I am running cmcWald on single gene and i am getting multiple same variants as output with different pvalues. Is it some kind of bug? Its happening only with cmcWALD? 
![image](https://user-images.githubusercontent.com/31892650/58130828-0c92f780-7beb-11e9-8b76-716476aceac1.png)

**Comment by apampana** [comment]
here is my code. /medpop/esp2/akhil/topmed/mend_genes/vcf_fh/executable/rvtest --inVcf name.vcf.gz --setFile try.set --pheno try.ped --pheno-name ldladj --qtl  --covar-name age,sex,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,ever_smoked --out ldlr --burden cmcWald --freqUpper 0.01

**Comment by apampana** [comment]
can u help me with this? 
Thank you

**Comment by zhanxw** [comment]
That is the estimations for different covariates (e.g., variant X:110688592, age, sex, PC1, ...) .
