### ISSUE TITLE
famSKAT stuck after loading kinship

### ISSUE THREAD

**Issue by apampana** [zhanxw/rvtests#87]
Hello 

I am running famskat on 50k samples and 300k variants and i am stuck within the same step of loading for last two days. Can you please help me with it?
```
/medpop/esp2/akhil/topmed/mend_genes/vcf_fh/executable/rvtest --inVcf fh_non_carriers.vcf.gz
--pheno fh_non_carr_no_amish.ped --pheno-name LDL_ADJ.norm
--covar-name age,age2,sex,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10  --single famLRT --kinship rvtest_kinship.kinship
--out sva  --numThread 1
```
this is the commnd i am using. please hep me thank you

**Comment by zhanxw** [comment]
famLRT model will fit the null once and the alternative model for every variant, so it is not practical to analyze using this famLRT.

**Comment by apampana** [comment]
What do you recommend for analysis as I want to do association based on kinship?

**Comment by zhanxw** [comment]
You can use famScore or famGrammarGamma.
