### ISSUE TITLE
Allele frequency and covariate outputs

### ISSUE THREAD

**Issue by medinacarolina** [zhanxw/rvtests#9]
Dear all, as usually the format required for the meta-analysis centers includes the allele frequency I was wondering if there is a flag to get this column in the output. This might be really important when analysing for example multi-ethnic cohorts as usually a frequency from a sample will not represent the frequency of the whole population (which can be easily obtained from .info files).

Also as in plink there is a flag "--hide-covar" to supress the covariates coefficients from the output... I was wondering if this flag exist or could be implemented in the program. 

Thanks a lot. Carolina

**Comment by zhanxw** [comment]
Hello Carolina,

When you use "--meta score", the allele frequency is outputted.
Did you use that option?

**Comment by medinacarolina** [comment]
Dear Zhan I am sorry if I confused you but I am runing a single variant analysis so my command is to this end 

../executable/rvtest --pheno pheno --inVcf example.vcf --single wald --out out1

And this command does not output does not report frequency, here the header

CHROM   POS     REF     ALT     N_INFORMATIVE   Test    Beta    SE      Pvalue



By using 
../executable/rvtest --pheno pheno --inVcf example.vcf --single wald --covar covar --covar-name c1,c2 --out out4

I get association results for all covariates (in my case 20 PCs for which I do not need the output and increase dramatically the size of my file... thats the reason I wanted to know if it is possible to have the option "--hide-covar" and get only the SNP association.

I hope now I have been clear. Best regards, Carolina

**Comment by medinacarolina** [comment]
thanks!

**Comment by m-makarious** [comment]
Hello, 
Regarding the --hide-covar flag, it seems as though it doesn't work when combined with trying to run the cmc Wald test? I've tried with and without the flag, but the output stays consistent (reporting one with all covariates accounted for, and one p-value per covariate as well)
